name: ci

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.1

      - name: Cache Astro assets
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.astro
          key: ${{ runner.os }}-astro-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-astro-

      - name: Install dependencies
        run: deno install --frozen=true

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.6.0
        id: install

      - name: Decrypt variables
        run: |-
          export SOPS_AGE_KEY=${{ secrets.SOPS_AGE_KEY }}
          sops decrypt .enc.env > .env

      - name: Build app
        run: deno task build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=portfolio
